const slides=[
{eyebrow:'پاسخ‌گویی هوشمند، سریع و همیشه در دسترس',title:'ایجنت‌یار، همراه هوشمند کسب‌وکار تو!',text:'دستیارهای هوش مصنوعی ایجنت‌یار روی اینستاگرام و واتساپ پاسخ می‌دهند، گفتگوها را پیگیری می‌کنند و مشتری را تا مرحله اقدام همراهی می‌کنند.',messages:[['in','سلام، خدمات احیا مو دارید؟'],['out','سلام 👋 بله. اگر نوع و وضعیت موهاتون رو بگید، راهنمایی‌تون می‌کنم.'],['in','موهام رنگ‌شده و خشکه'],['out','عالیه؛ دو خدمت مناسب دارید. دوست دارید قیمت و زمان‌های خالی رو هم براتون بفرستم؟']],status:'دستیار پاسخ‌گویی هوشمند فعال است'},
{eyebrow:'رزرو و نوبت‌دهی در سه کانال',title:'رزرو نوبت، بدون رفت‌وبرگشت اضافه',text:'دستیار رزرو ایجنت‌یار در اینستاگرام، واتساپ و تلگرام زمان‌های آزاد را پیشنهاد می‌دهد و نوبت مشتری را تا تایید نهایی جلو می‌برد.',messages:[['in','برای شنبه عصر وقت دارید؟'],['out','بله 👌 ساعت 16:00 و 18:30 خالیه. کدوم زمان براتون بهتره؟'],['in','18:30'],['out','انجام شد ✅ نوبت شما برای شنبه ساعت 18:30 ثبت شد.']],status:'دستیار رزرو و نوبت‌دهی فعال است'},
{eyebrow:'پیگیری خودکار گفتگوهای نیمه‌تمام',title:'هیچ فرصت فروش مهمی جا نمی‌ماند',text:'دستیار هوش مصنوعی مشتریان بدون پاسخ را دوباره پیگیری می‌کند و یادآوری نوبت را هم در زمان مناسب برای مشتری می‌فرستد.',messages:[['in','قیمت کراتین چقدره؟'],['out','قیمت نهایی به قد و حجم مو بستگی داره. اگر عکس بفرستید حدود قیمت رو می‌گم.'],['in','بعداً می‌فرستم'],['out','حتماً 🌱 هر زمان آماده بودید بفرستید؛ من گفتگو رو برای ادامه پیگیری نگه می‌دارم.']],status:'پیگیری خودکار گفتگو فعال است'}
];
let current=0,timer;const $=s=>document.querySelector(s);const eyebrow=$('#hero-eyebrow'),title=$('#hero-title'),text=$('#hero-text'),chat=$('#chat-box'),status=$('#bot-status-text'),dots=$('#carousel-dots');
function render(){const s=slides[current];eyebrow.textContent=s.eyebrow;title.textContent=s.title;text.textContent=s.text;chat.innerHTML=s.messages.map(([type,msg])=>`<div class="bubble ${type}">${msg}</div>`).join('');status.textContent=s.status;[...dots.children].forEach((d,i)=>d.classList.toggle('active',i===current));}
slides.forEach((_,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',`اسلاید ${i+1}`);b.onclick=()=>{current=i;render();restart()};dots.appendChild(b)});
function move(delta){current=(current+delta+slides.length)%slides.length;render();restart()}$('.prev').onclick=()=>move(-1);$('.next').onclick=()=>move(1);function restart(){clearInterval(timer);timer=setInterval(()=>move(1),6500)}render();restart();
const menuBtn=$('.menu-button'),mobile=$('#mobile-nav');menuBtn?.addEventListener('click',()=>{const open=menuBtn.getAttribute('aria-expanded')==='true';menuBtn.setAttribute('aria-expanded',String(!open));mobile.hidden=open});mobile?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobile.hidden=true;menuBtn.setAttribute('aria-expanded','false')}));
